# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c75ef06740ed24bc6559e568afab3aa4017fa30aad352b9a3e109d66480b903ade2e58bc1e894af77e7a96efcebb07ef80e4be93004ac2e64efae8b032741165

test:
  secret_key_base: 1239e816195f1c8f16b4e0ce9fe05123e417922cdcb4f1a170ea707080c475fd4d8a368fabefd202aea8b8d82a1d93c9950759a283ce6bc857916cf00c6ddfb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
